export const accountTypes = {
  'Caja': 'asset',
  'Banco': 'asset',
  'Clientes': 'asset',
  'Inventario': 'asset',
  'IVA Acreditado': 'asset',
  'IVA por Acreditar': 'asset',
  'Papelería': 'asset',
  'Papeleria': 'asset',
  'Rentas Pagadas x Antic.': 'asset',
  'Rentas pagadas por anticipado': 'asset',
  'Terreno': 'asset',
  'Edificio': 'asset',
  'Mobiliario': 'asset',
  'Eq. de Computo': 'asset',
  'Equipo de Cómputo': 'asset',
  'Eq. de Reparto': 'asset',
  'Equipo de Reparto': 'asset',
  'Eq. de Transporte': 'asset',
  'Equipo de Transporte': 'asset',
  'Gtos. de Instalacion': 'asset',
  'Gastos de Instalación': 'asset',
  'Depreciación Acumulada de Edificio': 'asset',
  'Depreciación Acumulada de Mobiliario': 'asset',
  'Depreciación Acumulada de Eq. Cómputo': 'asset',
  'Depreciación Acumulada de Eq. Reparto': 'asset',
  'Depreciación Acumulada de Eq. Transporte': 'asset',
  'Depreciación Acumulada de Gtos. Instalación': 'asset',
  'Doctos. por pagar': 'liability',
  'Documentos por pagar': 'liability',
  'IVA Trasladado': 'liability',
  'IVA por Trasladar': 'liability',
  'Anticipo de clientes': 'liability',
  'Capital': 'equity',
  'Capital Social': 'equity',
  'Resultado del Ejercicio': 'equity',
  'Ventas': 'revenue',
  'Costo de Ventas': 'expense',
  'Gastos de Venta': 'expense',
  'Gastos de Administración': 'expense',
  'Gastos de Depreciación': 'expense',
  'ISR 30%': 'expense',
  'PTU 10%': 'expense'
};